frutas = [
    'Maçã',
    'Banana',
    'Laranja',
    'Uva',
    'Morango',
    'Abacaxi',
    'Melancia',
    'Pera',
    'Manga',
    'Limão',
    'Cereja',
    'Kiwi',
    'Pêssego',
    'Ameixa',
    'Caju',
    'Pitaya',
    'Framboesa',
    'Goiaba',
    'Tangerina',
    'Melão',
    'Mirtilo',
    'Caqui',
    'Jabuticaba',
    'Physalis',
    'Carambola',
    'Cereja-do-Rio-Grande',
    'Coco',
    'Abacate',
    'Jaca',
    'Maracujá',
    'Amora',
    'Groselha',
    'Romã',
    'Lichia',
    'Açaí',
    'Carambola',
    'Pitanga',
    'Fruta-do-conde',
    'Cajá',
    'Graviola',
    'Figo',
    'Pêssego',
    'Caqui',
    'Nectarina',
    'Kiwano',
    'Melão-de-são-caetano',
    'Fruta-de-conde',
    'Coco-verde',
    'Mamão',
    'Cajá-manga',
    'Pitomba',
    'Cacau',
    'Pupunha',
    'Lima',
    'Fruta-pão',
    'Tamarindo',
    'Uxi',
    'Jambo',
    'Bacuri',
    'Tamarillo',
]

carnes = [
    'Filé Mignon',
    'Frango',
    'Picanha',
    'Alcatra',
    'Linguiça',
    'Peixe',
    'Costela',
    'Carne Moída',
    'Camarão',
    'Salmão',
    'Lombo',
    'Porco',
    'Cordeiro',
    'Coelho',
    'Pato',
    'Bife de Contrafilé',
    'Tilápia',
    'Bacalhau',
    'Atum',
    'Paleta de Porco',
    'Frango à Passarinho',
    'Miolo de Alcatra',
    'Maminha',
    'Pernil',
    'Filé de Peixe',
    'Toucinho',
    'Picanha Suína',
    'Linguiça Calabresa',
    'Lombo de Porco',
    'Salsicha',
    'Peru',
    'Costeleta de Porco',
    'Frango Desossado',
    'Bisteca',
    'Carne de Sol',
    'Bife de Chorizo',
    'Picanha Argentina',
    'Frango em Pedaços',
    'Filé de Tilápia',
    'Filé de Frango',
    'Linguiça Toscana',
    'Lagarto',
    'Capa de Filé',
    'Filé de Salmão',
    'Anchova',
    'Contrafilé de Porco',
    'Picanha Maturada',
    'Carne de Siri',
    'Costelinha de Porco',
    'Peito de Peru',
    'Peito de Frango',
    'Linguiça de Frango',
    'Picanha de Porco',
    'Filé de Merluza',
    'Lula',
    'Carne Seca',
    'Coxa de Frango',
    'Sardinha',
    'Barriga de Porco',
    'Lombo Suíno',
    'Carne de Caranguejo',
    'Coração de Frango',
]

congelados = [
    'Pizza',
    'Hambúrguer',
    'Lasanha',
    'Batata Frita',
    'Sorvete',
    'Peixe empanado',
    'Nuggets de frango',
    'Pão de queijo',
    'Coxinha',
    'Pastel',
    'Croissant',
    'Empanada',
    'Torta',
    'Esfiha',
    'Camarão empanado',
    'Pão de batata recheado',
    'Brigadeiro',
    'Churros',
    'Mandioca frita',
    'Coxinha de frango',
    'Empada',
    'Kibe',
    'Bolinho de bacalhau',
    'Bolinho de queijo',
    'Rissole',
    'Creme de açaí',
    'Pudim',
    'Massa para lasanha',
    'Sorvete de creme',
    'Sorvete de chocolate',
    'Sorvete de morango',
    'Sorvete de baunilha',
    'Sorvete de flocos',
    'Sorvete de maracujá',
    'Sorvete de limão',
    'Sorvete de uva',
    'Sorvete de abacaxi',
    'Sorvete de coco',
    'Coxinha de frango com catupiry',
    'Empadão',
    'Torta salgada',
    'Quiche',
    'Bolinho de carne',
    'Bolinho de aipim com carne seca',
    'Bolinho de feijoada',
    'Bolinho de camarão',
    'Rocambole',
    'Bolinho de queijo com presunto',
    'Pão de queijo com requeijão',
    'Pizza de calabresa',
    'Pizza de mussarela',
    'Pizza de frango com catupiry',
    'Pizza de margherita',
    'Pizza de peperoni',
    'Pizza de quatro queijos',
    'Pizza de portuguesa',
    'Pizza de bacon',
    'Pizza de banana com chocolate',
    'Pizza de abacaxi com presunto',
]

laticinios = [
    'Leite',
    'Queijo',
    'Iogurte',
    'Manteiga',
    'Requeijão',
    'Nata',
    'Coalhada',
    'Creme de Leite',
    'Leite Condensado',
    'Sorvete',
    'Iogurte Grego',
    'Queijo Mussarela',
    'Queijo Parmesão',
    'Queijo Provolone',
    'Queijo Minas',
    'Queijo Gorgonzola',
    'Queijo Prato',
    'Queijo Cottage',
    'Queijo Roquefort',
    'Queijo Ricota',
    'Queijo Brie',
    'Queijo Camembert',
    'Queijo Cheddar',
    'Queijo Gouda',
    'Queijo Emmental',
    'Queijo Reino',
    'Queijo Edam',
    'Queijo Feta',
    'Leite de Coco',
    'Leite de Amêndoas',
    'Leite de Aveia',
    'Leite de Soja',
    'Leite de Arroz',
    'Iogurte Natural',
    'Iogurte de Morango',
    'Iogurte de Frutas Vermelhas',
    'Iogurte de Banana',
    'Iogurte de Baunilha',
    'Iogurte de Cereja',
    'Iogurte de Abacaxi',
    'Iogurte de Manga',
    'Manteiga com Sal',
    'Manteiga sem Sal',
    'Requeijão Cremoso',
    'Requeijão Light',
    'Coalhada Seca',
    'Coalhada Tradicional',
    'Creme de Leite Fresco',
    'Creme de Leite de Caixinha',
    'Leite Condensado Tradicional',
    'Leite Condensado Light',
    'Sorvete de Chocolate',
    'Sorvete de Baunilha',
    'Sorvete de Morango',
    'Sorvete de Creme',
    'Sorvete de Flocos',
    'Sorvete de Pistache',
    'Sorvete de Limão',
    'Sorvete de Uva',
    'Sorvete de Abacaxi',
    'Sorvete de Coco',
]

limpeza = [
    'Detergente',
    'Sabão em pó',
    'Desinfetante',
    'Amaciante',
    'Água sanitária',
    'Limpador multiuso',
    'Esponja de limpeza',
    'Pano de limpeza',
    'Lustra-móveis',
    'Limpa-vidros',
    'Limpa-banheiro',
    'Desengordurante',
    'Alvejante',
    'Sabão líquido',
    'Sabonete',
    'Sabão em barra',
    'Removedor de manchas',
    'Álcool',
    'Desodorizador de ambiente',
    'Saco de lixo',
    'Inseticida',
    'Vassoura',
    'Rodo',
    'Balde',
    'Pá de lixo',
    'Aspirador de pó',
    'Panos de chão',
    'Pano de prato',
    'Pano de microfibra',
    'Escova de limpeza',
    'Escova sanitária',
    'Luvas de limpeza',
    'Mop',
    'Saco de aspirador de pó',
    'Bucha de limpeza',
    'Escova de cerdas',
    'Flanela',
    'Rodo mágico',
    'Desengripante',
    'Cera para piso',
    'Inseticida em aerossol',
    'Limpador de metais',
    'Desodorizador de geladeira',
    'Saco para aspirador de pó',
    'Fósforo',
    'Rolo adesivo para limpeza',
    'Odorizador de ambiente',
    'Escova para limpeza de roupas',
    'Vassoura de piaçava',
    'Escova para limpeza de carpete',
    'Escova para limpeza de azulejo',
    'Vassoura mágica',
    'Escova de limpeza de vasos sanitários',
    'Balde espremedor',
    'Cesto para lixo',
    'Limpador para fogão',
    'Rolo adesivo para remoção de pelos',
]

cereais = [
    'Arroz',
    'Feijão',
    'Milho',
    'Trigo',
    'Aveia',
    'Cevada',
    'Granola',
    'Farinha de Trigo',
    'Farinha de Milho',
    'Farinha de Aveia',
    'Flocos de Milho',
    'Flocos de Arroz',
    'Fubá',
    'Quinoa',
    'Semente de Chia',
    'Semente de Linhaça',
    'Macarrão',
    'Massa de Lasanha',
    'Cuscuz',
    'Pão de Forma',
    'Pão de Centeio',
    'Pão Integral',
    'Pão Francês',
    'Cereal Matinal',
    'Biscoito de Arroz',
    'Biscoito de Milho',
    'Biscoito de Aveia',
    'Biscoito de Maisena',
    'Barra de Cereal',
    'Farofa Pronta',
    'Granola',
    'Pipoca',
    'Tapioca',
    'Farinha de Mandioca',
    'Bolacha de Água e Sal',
    'Bolacha Recheada',
    'Bolacha de Maisena',
    'Bolacha de Chocolate',
    'Bolacha de Aveia',
    'Pão Sírio',
    'Pão de Queijo',
    'Pão de Hambúrguer',
    'Pão de Hot Dog',
    'Pão Integral',
    'Cereal Infantil',
    'Farelo de Aveia',
    'Farelo de Trigo',
    'Farelo de Arroz',
    'Biscoito de Polvilho',
    'Torrada',
    'Rosquinha',
    'Cereal de Arroz',
    'Cereal de Milho',
    'Cereal de Trigo',
    'Cereal de Aveia',
]

higiene_pessoal = [
    'Shampoo',
    'Condicionador',
    'Sabonete',
    'Creme Dental',
    'Desodorante',
    'Papel Higiênico',
    'Lenço de Papel',
    'Escova de Dentes',
    'Fio Dental',
    'Enxaguante Bucal',
    'Absorvente',
    'Protetor Diário',
    'Creme Hidratante',
    'Loção Corporal',
    'Perfume',
    'Hidratante Labial',
    'Gel de Banho',
    'Desodorante Roll-on',
    'Desodorante Aerosol',
    'Desodorante Creme',
    'Desodorante Stick',
    'Cotonete',
    'Algodão',
    'Barbeador',
    'Espuma de Barbear',
    'Gel para Cabelo',
    'Cera para Cabelo',
    'Máscara Facial',
    'Sabonete Líquido',
    'Sabonete Íntimo',
    'Loção Pós-barba',
    'Tônico Facial',
    'Escova de Cabelo',
    'Pente',
    'Pinça',
    'Creme Depilatório',
    'Desodorante Íntimo',
    'Hastes Flexíveis',
    'Curativo',
    'Antisséptico Bucal',
    'Esmalte',
    'Removedor de Esmalte',
    'Acetona',
    'Lixa de Unha',
    'Hidratante para Mãos',
    'Hidratante para Pés',
    'Creme para Assaduras',
    'Absorvente Noturno',
    'Sabonete Íntimo Masculino',
    'Desodorante Íntimo Masculino',
    'Desodorante Íntimo Feminino',
    'Creme de Barbear',
    'Colônia',
    'Perfume',
    'Máscara de Cílios',
    'Batom',
    'Base',
    'Corretivo',
    'Blush',
]

limpeza = [
    'Detergente',
    'Sabão em Pó',
    'Amaciante',
    'Água Sanitária',
    'Desinfetante',
    'Limpador Multiuso',
    'Esponja',
    'Pano de Limpeza',
    'Limpador de Vidros',
    'Lustra Móveis',
    'Limpa Banheiro',
    'Limpa Forno',
    'Limpa Carpete',
    'Limpa Piso',
    'Saco de Lixo',
    'Inseticida',
    'Repelente',
    'Vassoura',
    'Rodo',
    'Mop',
    'Pá de Lixo',
    'Balde',
    'Escova de Limpeza',
    'Pano de Chão',
    'Pano de Prato',
    'Pano de Pia',
    'Limpador Perfumado',
    'Limpador de Alumínio',
    'Limpador de Inox',
    'Limpador de Azulejo',
    'Limpador de Granito',
    'Limpador de Mármore',
    'Limpador de Aço Inox',
    'Limpa Vidros',
    'Saponáceo',
    'Limpa Carpete',
    'Limpa Estofados',
    'Limpa Couro',
    'Limpa Vidro',
    'Limpa Pisos',
    'Desengordurante',
    'Tira Manchas',
    'Pasta de Limpeza',
    'Cera Líquida',
    'Polidor de Móveis',
    'Cera em Pasta',
    'Cera em Gel',
    'Limpa Rejuntes',
    'Removedor de Ferrugem',
    'Água de Passar',
    'Limpador de Janelas',
    'Água de Passar',
    'Tira-limo',
    'Tira-mofo',
    'Odorizador de Ambiente',
    'Sabão Líquido',
    'Sabão em Barra',
    'Cloro',
    'Amaciante Concentrado',
    'Amaciante para Roupas',
    'Amaciante Perfumado',
    'Lustra Móveis Aerosol',
    'Lustra Móveis em Gel',
    'Lustra Móveis em Spray',
    'Limpador de Banheiro',
    'Limpador de Cozinha',
]

# Crie uma lista final contendo todas as categorias
supermercado = [frutas, carnes, laticinios, cereais, higiene_pessoal, limpeza]

# Verifique o número total de produtos
numero_produtos = sum(len(categoria) for categoria in supermercado)
print("Número total de produtos:", numero_produtos)
